# fly.toml app configuration file generated for slink on 2025-08-07T15:42:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slink'
primary_region = 'nrt'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  ECTO_IPV6 = 'true'
  ERL_AFLAGS = '-proto_dist inet6_tcp'
  MAILER_SMTP_GMAIL_ENABLED = 'true'
  PHX_HOST = 'slink.fly.dev'
  PORT = '8080'
  RELEASE_COOKIE = 'happy-cookie-not-secret-but-for-cluster'
  RELEASE_DISTRIBUTION = 'name'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
